     - name: Install Java
       yum:
         name: java
         state: latest

     - name: Download Tomcat
       get_url:
         dest: /opt
         mode: 493
         url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz"

     - name: unarchive Tomcat 8 tar file
       unarchive:
         dest: /opt
         src: /opt/apache-tomcat-8.0.32.tar.gz

     - name: Delete directory if exist
       file:
         name: /opt/tomcat-8
         state: absent

     - name: Rename Tomcat8 Directory
       command: "mv /opt/apache-tomcat-8.0.32 /opt/tomcat-8"

     - name: Download Jenkins into the webapps folder in Tomcat
       get_url:
         url: https://get.jenkins.io/war-stable/2.263.4/jenkins.war
         dest: /opt/tomcat-8/webapps

     - name: Create tomcat user
       copy:
         src: roles/tomcat8/files/tomcat-users.xml
         dest: /opt/tomcat-8/conf/tomcat-users.xml
         mode: 0755

     - name: Make tomcat.service
       copy:
         src: roles/tomcat8/files/tomcat.service
         dest: /etc/systemd/system/tomcat.service
         mode: 0755

     - name: start tomcat.service
       systemd:
         name: tomcat
         state: started
         daemon_reload: yes
       
